const HomeConfig = [
  {
    type: "text",
    name: "Name",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name2",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name3",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name4",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name5",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name6",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name7",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name8",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name9",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name10",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name11",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name12",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name13",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name14",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name15",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name16",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name17",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name18",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name19",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name20",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name21",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name22",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name23",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name24",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name25",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name26",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name27",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name28",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "text",
    name: "Name29",
    placeholder: "Name",
    ariaLabel: "Name",
    defaultValue: "",
    autofill: "",
    prefix: { display: false, children: "" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[\\p{L} .'-]+$",
    min: undefined,
    max: undefined,
    minLength: 2,
    maxLength: undefined,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid name",
      patternMismatch: "Please enter a valid name",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Name is too long",
      tooShort: "Name is too short",
      typeMismatch: "Please enter a valid name",
      valid: "Please enter a valid name",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid name",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "text-capitalize",
      },
    },
  },
  {
    type: "tel",
    name: "Tel",
    placeholder: "Phone No.",
    ariaLabel: "Phone No.",
    defaultValue: "",
    autofill: "",
    prefix: { display: true, children: "+91" },
    suffix: { display: false, children: "" },
    disabled: false,
    required: true,
    pattern: "^[0-9]+$",
    min: undefined,
    max: undefined,
    minLength: 10,
    maxLength: 10,
    spellcheck: false,
    errorCases: {
      badInput: "Please enter a valid Phone No.",
      patternMismatch: "Please enter a valid Phone No.",
      rangeOverflow: "",
      rangeUnderflow: "",
      stepMismatch: "",
      tooLong: "Phone No. is too long",
      tooShort: "Phone No. is too short",
      typeMismatch: "Please enter a valid Phone No.",
      valid: "Please enter a valid Phone No.",
      valueMissing: "This is a mandatory field",
      defaultValid: "Looks good",
      defaultInvalid: "Please enter a valid Phone No.",
    },
    layout: {
      width: "col-4",
      children: {
        textDecoration: "",
      },
    },
  },
];

export default HomeConfig;
